name: Bundle Webpack

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  bundle-webpack:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v4
    -
      uses: actions/setup-node@v4
      with:
        node-version: lts/hydrogen
    - run: npm ci
    - run: npm run build
    - run: npm -w packages/webmavryk-local-forging run build-webpack
    -
      uses: actions/upload-artifact@v4
      with:
        name: webmavryk-local-forging-vanilla
        path: |
          packages/webmavryk-local-forging/dist/webmavryk_local_forging.js
          packages/webmavryk-local-forging/dist/webmavryk_local_forging.js.map

    - run: npm -w packages/webmavryk-mavlet-wallet run build-webpack
    -
      uses: actions/upload-artifact@v4
      with:
        name: webmavryk-mavlet-wallet-vanilla
        path: |
          packages/webmavryk-mavlet-wallet/dist/webmavryk_mavlet_wallet.js
          packages/webmavryk-mavlet-wallet/dist/webmavryk_mavlet_wallet.js.map
